// src/lib/data.ts

export const DIVISIONS = [
  "Dhaka",
  "Chattogram",
  "Khulna",
  "Rajshahi",
  "Barishal",
  "Sylhet",
  "Rangpur",
  "Mymensingh",
] as const;

export const DIVISIONS_ALL = [...DIVISIONS, "Other"] as const;

export type Division = typeof DIVISIONS_ALL[number];

export const DIVISIONS_BN: Record<string, string> = {
  Dhaka: "ঢাকা",
  Chattogram: "চট্টগ্রাম",
  Khulna: "খুলনা",
  Rajshahi: "রাজশাহী",
  Barishal: "বরিশাল",
  Sylhet: "সিলেট",
  Rangpur: "রংপুর",
  Mymensingh: "ময়মনসিংহ",
  Other: "অন্যান্য",
};

export const BLOOD_GROUPS = [
  "A+",
  "A-",
  "B+",
  "B-",
  "AB+",
  "AB-",
  "O+",
  "O-",
] as const;

export type BloodGroup = typeof BLOOD_GROUPS[number];

export type CancerType =
  | "general"
  | "blood"
  | "skin"
  | "lung"
  | "breast"
  | "cervical"
  | "surgery"
  | "gynae"
  | "pediatrics"
  | "cardiology"
  | "oncology";

export const CANCER_LABELS: Record<CancerType, string> = {
  general: "General Medicine / Specialist",
  blood: "Blood (Leukemia / Lymphoma)",
  skin: "Skin (Melanoma)",
  lung: "Lung",
  breast: "Breast",
  cervical: "Cervical",
  surgery: "General & Laparoscopic Surgery",
  gynae: "Gynecology & Obstetrics",
  pediatrics: "Pediatrics & Child Health",
  cardiology: "Cardiology & Heart Specialist",
  oncology: "Radiation & Clinical Oncology",
};

export const CANCER_LABELS_BN: Record<CancerType, string> = {
  general: "মেডিসিন বিশেষজ্ঞ",
  blood: "রক্ত ক্যান্সার",
  skin: "ত্বক ক্যান্সার",
  lung: "ফুসছুস ক্যান্সার",
  breast: "স্তন ক্যান্সার",
  cervical: "জরায়ুমুখ ক্যান্সার",
  surgery: "সার্জারি বিশেষজ্ঞ",
  gynae: "গাইনি ও প্রসূতি রোগ",
  pediatrics: "শিশু রোগ বিশেষজ্ঞ",
  cardiology: "হৃদরোগ বিশেষজ্ঞ",
  oncology: "অনকোলজি (ক্যান্সার বিশেষজ্ঞ)",
};

export interface DoctorType {
  name: string;
  name_bn: string;
  specialty: CancerType;
  specialty_bn: string;
  division: string;
  division_bn: string;
  hospital: string;
  hospital_bn: string;
  degree: string;
  degree_bn: string;
  phone: string;
  schedule: string;
  schedule_bn: string;
  chamber: string;
  chamber_bn: string;
}

export const DOCTORS: DoctorType[] = [
  {
    name: "Assistant Professor Dr. Jyotirmoy Chowdhury",
    name_bn: "সহকারী অধ্যাপক ড. জ্যোতির্ময় চৌধুরী",
    specialty: "breast",
    specialty_bn: "স্তন ক্যান্সার",
    division: "Dhaka",
    division_bn: "ঢাকা",
    hospital: "Square Hospital",
    hospital_bn: "স্কয়ার হাসপাতাল",
    degree: "MBBS, BCS (Health), MS (Urology)",
    degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এমএস (ইউরোলজি)",
    phone: "01789-565123",
    schedule: "Sat - Thu (5:00 PM - 9:00 PM)",
    schedule_bn: "শনি - বৃহস্পতি (বিকাল ৫:০০ - রাত ৯:০০)",
    chamber: "Chamber Building, Floor 3, Square Hospital, Dhaka",
    chamber_bn: "চেম্বার বিল্ডিং, ৩য় তলা, স্কয়ার হাসপাতাল, ঢাকা",
  },
  {
    name: "Dr. Asif Karim",
    name_bn: "ডা. আসিফ করিম",
    specialty: "lung",
    specialty_bn: "ফুসফুস ক্যান্সার",
    division: "Dhaka",
    division_bn: "ঢাকা",
    hospital: "United Hospital",
    hospital_bn: "ইউনাইটেড হাসপাতাল",
    degree: "MBBS, FCPS (Medicine), MD (Chest Diseases)",
    degree_bn: "এমবিবিএস, এফসিপিএস (মেডিসিন), এমডি (বক্ষব্যাধি)",
    phone: "01860-557199",
    schedule: "Sun - Thu (4:00 PM - 8:00 PM)",
    schedule_bn: "রবি - বৃহস্পতি (বিকাল ৪:০০ - রাত ৮:০০)",
    chamber: "Main OPD Block, United Hospital, Gulshan, Dhaka",
    chamber_bn: "মূল ওপিডি ব্লক, ইউনাইটেড হাসপাতাল, গুলশান, ঢাকা",
  },
  {
    name: "Dr. Sumi Akter",
    name_bn: "ডা. সুমি আক্তার",
    specialty: "cervical",
    specialty_bn: "জরায়ুমুখ ক্যান্সার",
    division: "Dhaka",
    division_bn: "ঢাকা",
    hospital: "BSMMU",
    hospital_bn: "বিএসএমএমইউ",
    degree: "MBBS, MS (Gynae & Obs)",
    degree_bn: "এমবিবিএস, এমএস (গাইনি অ্যান্ড অব্স)",
    phone: "01711-223344",
    schedule: "Sat, Mon, Wed (5:00 PM - 8:30 PM)",
    schedule_bn: "শনি, সোম, বুধ (বিকাল ৫:০০ - রাত ৮:৩০)",
    chamber: "Green Road Doctors Center, Dhanmondi, Dhaka",
    chamber_bn: "গ্রিন রোড ডক্টরস সেন্টার, ধানমন্ডি, ঢাকা",
  },
  {
    name: "Dr. Rezaul Hoque",
    name_bn: "ডা. রেজাউল হক",
    specialty: "blood",
    specialty_bn: "রক্ত ক্যান্সার",
    division: "Dhaka",
    division_bn: "ঢাকা",
    hospital: "Dhaka Medical College",
    hospital_bn: "ঢাকা মেডিকেল কলেজ",
    degree: "MBBS, FCPS (Hematology)",
    degree_bn: "এমবিবিএস, এফসিপিএস (হেমাটোলজি)",
    phone: "01552-667788",
    schedule: "Sun - Wed (4:00 PM - 7:00 PM)",
    schedule_bn: "রবি - বুধ (বিকাল ৪:০০ - সন্ধ্যা ৭:০০)",
    chamber: "Popular Diagnostic Center, Dhanmondi, Dhaka",
    chamber_bn: "পপুলার ডায়াগনস্টিক সেন্টার, ধানমন্ডি, ঢাকা",
  },
  {
    name: "Dr. Farhana Yasmin",
    name_bn: "ডা. ফারহানা ইয়াসমিন",
    specialty: "skin",
    specialty_bn: "ত্বক ক্যান্সার",
    division: "Dhaka",
    division_bn: "ঢাকা",
    hospital: "Labaid",
    hospital_bn: "ল্যাবএইড হাসপাতাল",
    degree: "MBBS, DDV (Dermatology)",
    degree_bn: "এমবিবিএস, ডিডিভি (ডার্মাটোলজি)",
    phone: "01611-334455",
    schedule: "Sat - Thu (6:00 PM - 9:30 PM)",
    schedule_bn: "শনি - বৃহস্পতি (সন্ধ্যা  ৬:০০ - রাত ৯:৩০)",
    chamber: "Labaid Building 2, Dhanmondi, Dhaka",
    chamber_bn: "ল্যাবএইড বিল্ডিং ২, ধানমন্ডি, ঢাকা",
  },
  {
    name: "Dr. Mahbub Alam",
    name_bn: "ডা. মাহবুব আলম",
    specialty: "lung",
    specialty_bn: "ফুসফুস ক্যান্সার",
    division: "Chattogram",
    division_bn: "চট্টগ্রাম",
    hospital: "CMCH",
    hospital_bn: "চট্টগ্রাম মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, MD (Chest)",
    degree_bn: "এমবিবিএস, এমডি (বক্ষব্যাধি)",
    phone: "01311-016354",
    schedule: "Sat - Wed (5:00 PM - 8:00 PM)",
    schedule_bn: "শনি - বুধ (বিকাল ৫:০০ - রাত ৮:০০)",
    chamber: "Epic Healthcare, Chawkbazar, Chattogram",
    chamber_bn: "এপিক হেলথকেয়ার, চকবাজার, চট্টগ্রাম",
  },
  {
    name: "Dr. Rumana Haque",
    name_bn: "ডা. রুমানা হক",
    specialty: "breast",
    specialty_bn: "স্তন ক্যান্সার",
    division: "Chattogram",
    division_bn: "চট্টগ্রাম",
    hospital: "Imperial Hospital",
    hospital_bn: "ইম্পেরিয়াল হাসপাতাল",
    degree: "MBBS, FCPS, MS (Surgical Oncology)",
    degree_bn: "এমবিবিএস, এফসিপিএস, এমএস (সার্জিক্যাল অনকোলজি)",
    phone: "01819-876543",
    schedule: "Mon - Wed (6:00 PM - 9:00 PM)",
    schedule_bn: "সোম - বুধ (সন্ধ্যা ৬:০০ - রাত ৯:০০)",
    chamber: "Imperial Consultations Wing, Chattogram",
    chamber_bn: "ইম্পেরিয়াল কনসালটেশন উইং, চট্টগ্রাম",
  },
  {
    name: "Dr. Nazmul Islam",
    name_bn: "ডা. নাজমুল ইসলাম",
    specialty: "blood",
    specialty_bn: "রক্ত ক্যান্সার",
    division: "Chattogram",
    division_bn: "চট্টগ্রাম",
    hospital: "Evercare Hospital Chattogram",
    hospital_bn: "এভারকেয়ার হাসপাতাল চট্টগ্রাম",
    degree: "MBBS, MD (Hematology)",
    degree_bn: "এমবিবিএস, এমডি (হেমাটোলজি)",
    phone: "01400-112233",
    schedule: "Sat - Thu (3:00 PM - 7:00 PM)",
    schedule_bn: "শনি - বৃহস্পতি (দুপুর ৩:০০ - সন্ধ্যা ৭:০০)",
    chamber: "Evercare Clinic Tower, Anowara, Chattogram",
    chamber_bn: "এভারকেয়ার ক্লিনিক টাওয়ার, আনোয়ারা, চট্টগ্রাম",
  },
  {
    name: "Dr. Tania Chowdhury",
    name_bn: "ডা. তানিয়া চৌধুরী",
    specialty: "cervical",
    specialty_bn: "জরায়ুমুখ ক্যান্সার",
    division: "Sylhet",
    division_bn: "সিলেট",
    hospital: "Sylhet MAG Osmani",
    hospital_bn: "সিলেট এমএজি ওসমানী মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, MS (Gynae)",
    degree_bn: "এমবিবিএস, এমএস (গাইনি)",
    phone: "01912-998877",
    schedule: "Sun - Tue (5:00 PM - 8:00 PM)",
    schedule_bn: "রবি - মঙ্গল (বিকাল ৫:০০ - রাত ৮:০০)",
    chamber: "Oasis Hospital, Subhanighat, Sylhet",
    chamber_bn: "ওয়েসিস হাসপাতাল, সুভানীঘাট, সিলেট",
  },
  {
    name: "Dr. Imran Hossain",
    name_bn: "ডা. ইমরান হোসেন",
    specialty: "skin",
    specialty_bn: "ত্বক ক্যান্সার",
    division: "Sylhet",
    division_bn: "সিলেট",
    hospital: "Mount Adora",
    hospital_bn: "মাউন্ট অ্যাডোরা হাসপাতাল",
    degree: "MBBS, DDV (Skin & Venereal)",
    degree_bn: "এমবিবিএস, ডিডিভি (চর্ম ও যৌন)",
    phone: "01715-445566",
    schedule: "Sat - Thu (4:30 PM - 8:30 PM)",
    schedule_bn: "শনি - বৃহস্পতি (বিকাল ৪:৩০ - রাত ৮:৩০)",
    chamber: "Mount Adora Complex, Akhalia, Sylhet",
    chamber_bn: "মাউন্ট অ্যাডোরা কমপ্লেক্স, আখালিয়া, সিলেট",
  },
  {
    name: "Dr. Sadia Sultana",
    name_bn: "ডা. সাদিয়া সুলতানা",
    specialty: "breast",
    specialty_bn: "স্তন ক্যান্সার",
    division: "Khulna",
    division_bn: "খুলনা",
    hospital: "Khulna Medical",
    hospital_bn: "খুলনা মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, MS (General Surgery)",
    degree_bn: "এমবিবিএস, এমএস (জেনারেল সার্জারি)",
    phone: "01811-556677",
    schedule: "Sat, Mon, Wed (4:00 PM - 7:30 PM)",
    schedule_bn: "শনি, সোম, বুধ (বিকাল ৪:০০ - সন্ধ্যা ৭:৩০)",
    chamber: "City Medical Center Chambers, Khulna",
    chamber_bn: "সিটি মেডিকেল সেন্টার চেম্বারস, খুলনা",
  },
  {
    name: "Dr. Kamrul Hasan",
    name_bn: "ডা. কামরুল হাসান",
    specialty: "lung",
    specialty_bn: "ফুসফুস ক্যান্সার",
    division: "Khulna",
    division_bn: "খুলনা",
    hospital: "Gazi Medical",
    hospital_bn: "গাজী মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, MD (Chest)",
    degree_bn: "এমবিবিএস, এমডি (বক্ষব্যাধি)",
    phone: "01677-112233",
    schedule: "Sun - Thu (5:00 PM - 9:00 PM)",
    schedule_bn: "রবি - বৃহস্পতি (বিকাল ৫:০০ - রাত ৯:০০)",
    chamber: "Gazi Medical Outpatient Wing, Khulna",
    chamber_bn: "গাজী মেডিকেল বহির্বিভাগ উইং, খুলনা",
  },
  {
    name: "Dr. Mohsin Khan",
    name_bn: "ডা. মঈন খান",
    specialty: "blood",
    specialty_bn: "রক্ত ক্যান্সার",
    division: "Rajshahi",
    division_bn: "রাজশাহী",
    hospital: "Rajshahi Medical",
    hospital_bn: "রাজশাহী মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, FCPS (Hematology)",
    degree_bn: "এমবিবিএস, এফসিপিএস (হেমাটোলজি)",
    phone: "01511-998877",
    schedule: "Sat - Wed (4:00 PM - 8:00 PM)",
    schedule_bn: "শনি - বুধ (বিকাল ৪:০০ - রাত ৮:০০)",
    chamber: "Zamzam Hospital, Laxmipur, Rajshahi",
    chamber_bn: "জমজম হাসপাতাল, লক্ষ্মীপুর, রাজশাহী",
  },
  {
    name: "Dr. Lubna Akhter",
    name_bn: "ডা. লুবনা আক্তার",
    specialty: "cervical",
    specialty_bn: "জরায়ুমুখ ক্যান্সার",
    division: "Rajshahi",
    division_bn: "রাজশাহী",
    hospital: "Islami Bank Hospital",
    hospital_bn: "ইসলামী ব্যাংক হাসপাতাল",
    degree: "MBBS, MS (Gynae & Obs)",
    degree_bn: "এমবিবিএস, এমএস (গাইনি ও প্রসূতি)",
    phone: "01722-334455",
    schedule: "Sat - Thu (5:00 PM - 8:30 PM)",
    schedule_bn: "শনি - বৃহস্পতি (বিকাল ৫:০০ - রাত ৮:৩০)",
    chamber: "Islami Bank Hospital, Medical Road, Rajshahi",
    chamber_bn: "ইসলামী ব্যাংক হাসপাতাল, মেডিকেল রোড, রাজশাহী",
  },
  {
    name: "Dr. Shafiqul Bari",
    name_bn: "ডা. শফিকুল বারী",
    specialty: "skin",
    specialty_bn: "ত্বক ক্যান্সার",
    division: "Barishal",
    division_bn: "বরিশাল",
    hospital: "Sher-e-Bangla Medical",
    hospital_bn: "শের-ই-বাংলা মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, DDV, FCPS",
    degree_bn: "এমবিবিএস, ডিডিভি, এফসিপিএস",
    phone: "01911-556677",
    schedule: "Sun - Thu (4:00 PM - 7:30 PM)",
    schedule_bn: "রবি - বৃহস্পতি (বিকাল ৪:০০ - সন্ধ্যা ৭:৩০)",
    chamber: "Bellview Medical Center, Barishal",
    chamber_bn: "বেলভিউ মেডিকেল সেন্টার, বরিশাল",
  },
  {
    name: "Dr. Mizanur Rahman",
    name_bn: "ডা. মিজানুর রহমান",
    specialty: "lung",
    specialty_bn: "ফুসফুস ক্যান্সার",
    division: "Rangpur",
    division_bn: "রংপুর",
    hospital: "Rangpur Medical",
    hospital_bn: "রংপুর মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, DTCD (Chest Diseases)",
    degree_bn: "এমবিবিএস, ডিটিসিডি (বক্ষব্যাধি)",
    phone: "01322-990011",
    schedule: "Sat - Wed (5:00 PM - 9:00 PM)",
    schedule_bn: "শনি - বুধ (বিকাল ৫:০০ - রাত ৯:০০)",
    chamber: "Good Health Hospital, Dhap, Rangpur",
    chamber_bn: "গুড হেলথ হাসপাতাল, ধাপ, রংপুর",
  },
  {
    name: "Dr. Afrin Jahan",
    name_bn: "ডা. আফরিন জাহান",
    specialty: "breast",
    specialty_bn: "স্তন ক্যান্সার",
    division: "Mymensingh",
    division_bn: "ময়মনসিংহ",
    hospital: "Mymensingh Medical",
    hospital_bn: "ময়মনসিংহ মেডিকেল কলেজ হাসপাতাল",
    degree: "MBBS, MS (Surgical Oncology)",
    degree_bn: "এমবিবিএস, এমএস (সার্জিক্যাল অনকোলজি)",
    phone: "01855-223344",
    schedule: "Sat - Thu (4:00 PM - 8:00 PM)",
    schedule_bn: "শনি - বৃহস্পতি (বিকাল ৪:০০ - রাত ৮:০০)",
    chamber: "Nexus Hospital Chambers, Mymensingh",
    chamber_bn: "নেক্সাস হাসপাতাল চেম্বারস, ময়মনসিংহ",
  },
  {
    name: "Dr. M. A. Masud",
    name_bn: "ডা. এম. এ. মাসুদ",
    specialty: "surgery",
    specialty_bn: "সার্জারি বিশেষজ্ঞ",
    division: "Barishal",
    division_bn: "বরিশাল",
    hospital: "South Real Hospital",
    hospital_bn: "সাউথ রিয়েল হাসপাতাল",
    degree: "MBBS, FCPS (Surgery)",
    degree_bn: "এমবিবিএস, এফসিপিএস (সার্জারি)",
    phone: "01712-889900",
    schedule: "Sat - Thu (4:00 PM - 8:00 PM)",
    schedule_bn: "শনি - বৃহস্পতি (বিকাল ৪:০০ - রাত ৮:০০)",
    chamber: "South Real Hospital, Band Road, Barishal",
    chamber_bn: "সাউথ রিয়েল হাসপাতাল, ব্যান্ড রোড, বরিশাল",
  },
  {
    name: "Prof. Dr. Shamim Ahmed",
    name_bn: "অধ্যাপক ড. শামীম আহমেদ",
    specialty: "cardiology",
    specialty_bn: "হৃদরোগ বিশেষজ্ঞ",
    division: "Dhaka",
    division_bn: "ঢাকা",
    hospital: "National Heart Foundation",
    hospital_bn: "ন্যাশনাল হার্ট ফাউন্ডেশন",
    degree: "MBBS, MD (Cardiology), FCPS",
    degree_bn: "এমবিবিএস, এমডি (কার্ডিওলজি), এফসিপিএস",
    phone: "01911-445522",
    schedule: "Sat - Wed (5:00 PM - 9:00 PM)",
    schedule_bn: "শনি - বুধ (বিকাল ৫:০০ - রাত ৯:০০)",
    chamber: "National Heart Foundation Diagnostic Wing, Mirpur, Dhaka",
    chamber_bn: "ন্যাশনাল হার্ট ফাউন্ডেশন ডায়াগনস্টিক উইং, মিরপুর, ঢাকা",
  },
  {
    name: "Dr. Naila Zaman",
    name_bn: "ডা. নায়লা জামান",
    specialty: "pediatrics",
    specialty_bn: "শিশু রোগ বিশেষজ্ঞ",
    division: "Chattogram",
    division_bn: "চট্টগ্রাম",
    hospital: "Chattogram International Medical College",
    hospital_bn: "চট্টগ্রাম আন্তর্জাতিক মেডিকেল কলেজ",
    degree: "MBBS, DCH (Pediatrics), FCPS",
    degree_bn: "এমবিবিএস, ডিসিএইচ (পেডিয়াট্রিক্স), এফসিপিএস",
    phone: "01815-334411",
    schedule: "Sun - Thu (3:30 PM - 7:30 PM)",
    schedule_bn: "রবি - বৃহস্পতি (বিকাল ৩:৩০ - সন্ধ্যা ৭:৩০)",
    chamber: "Chevron Clinical Laboratory, Halishahar, Chattogram",
    chamber_bn: "শেভরন ক্লিনিক্যাল ল্যাবরেটরি, হালিশহর, চট্টগ্রাম",
  },
  {
    name: "Dr. Tanvir Rahman",
    name_bn: "ডা. তানভীর রহমান",
    specialty: "oncology",
    specialty_bn: "অনকোলজি (ক্যান্সার বিশেষজ্ঞ)",
    division: "Sylhet",
    division_bn: "সিলেট",
    hospital: "Sylhet Oncology Care Center",
    hospital_bn: "সিলেট অনকোলজি কেয়ার সেন্টার",
    degree: "MBBS, MD (Radiation Oncology)",
    degree_bn: "এমবিবিএস, এমডি (রেডিয়েশন অনকোলজি)",
    phone: "01712-336699",
    schedule: "Sat - Wed (5:00 PM - 9:00 PM)",
    schedule_bn: "শনি - বুধ (বিকাল ৫:০০ - রাত ৯:০০)",
    chamber: "Popular Medical Center, Kajalshah, Sylhet",
    chamber_bn: "পপুলার মেডিকেল সেন্টার, কাজলশাহ, সিলেট",
  },
  

{
  name: "Major Dr. Md. Enamul Islam",
  name_bn: "মেজর ডা. মোঃ এনামুল ইসলাম",
  specialty: "psychiatry" as any,
  specialty_bn: "মনোরোগ বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Bangladesh Navy Hospital",
  hospital_bn: "বাংলাদেশ নৌবাহিনী হাসপাতাল",
  degree: "MBBS, DPM, Graduate Course (Psychiatry), MRC Psych",
  degree_bn: "এমবিবিএস, ডিপিএম, সাইকিয়াট্রি গ্র্যাজুয়েট কোর্স, এমআরসি সাইক",
  phone: "01740-486123",
  schedule: "Sat - Thu (4:00 PM - 8:00 PM)",
  schedule_bn: "শনি - বৃহস্পতি (বিকাল ৪:০০ - রাত ৮:০০)",
  chamber: "Bangladesh Navy Hospital, Khulna",
  chamber_bn: "বাংলাদেশ নৌবাহিনী হাসপাতাল, খুলনা",
},

{
  name: "Assistant Professor Dr. Nahid Sultana",
  name_bn: "সহকারী অধ্যাপক ডা. নাহিদ সুলতানা",
  specialty: "general",
  specialty_bn: "মেডিসিন বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Shaheed Shaikh Abu Naser Specialized Hospital",
  hospital_bn: "শহীদ শেখ আবু নাসের বিশেষায়িত হাসপাতাল",
  degree: "MBBS, BCS (Health), MD (Physical Medicine & Rehabilitation)",
  degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এমডি (ফিজিক্যাল মেডিসিন)",
  phone: "01740-486124",
  schedule: "Sun - Thu (5:00 PM - 9:00 PM)",
  schedule_bn: "রবি - বৃহস্পতি (বিকাল ৫:০০ - রাত ৯:০০)",
  chamber: "Shaheed Shaikh Abu Naser Specialized Hospital, Khulna",
  chamber_bn: "শহীদ শেখ আবু নাসের বিশেষায়িত হাসপাতাল, খুলনা",
},

{
  name: "Dr. Kalpo Sikder",
  name_bn: "ডা. কল্প সিকদার",
  specialty: "general",
  specialty_bn: "মেডিসিন বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Shaheed Shaikh Abu Naser Specialized Hospital",
  hospital_bn: "শহীদ শেখ আবু নাসের বিশেষায়িত হাসপাতাল",
  degree: "MBBS, BCS (Health), MD (Neurology)",
  degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এমডি (নিউরোলজি)",
  phone: "01740-486125",
  schedule: "Sat - Wed (4:00 PM - 8:00 PM)",
  schedule_bn: "শনি - বুধ (বিকাল ৪:০০ - রাত ৮:০০)",
  chamber: "Shaheed Shaikh Abu Naser Specialized Hospital, Khulna",
  chamber_bn: "শহীদ শেখ আবু নাসের বিশেষায়িত হাসপাতাল, খুলনা",
},

{
  name: "Dr. Monirul Haque",
  name_bn: "ডা. মনিরুল হক",
  specialty: "general",
  specialty_bn: "মেডিসিন বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Khulna Medical College & Hospital",
  hospital_bn: "খুলনা মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS, BCS (Health), FCPS (Medicine), MRCP (UK)",
  degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এফসিপিএস (মেডিসিন), এমআরসিপি (ইউকে)",
  phone: "01740-486126",
  schedule: "Sun - Thu (5:00 PM - 8:30 PM)",
  schedule_bn: "রবি - বৃহস্পতি (বিকাল ৫:০০ - রাত ৮:৩০)",
  chamber: "Khulna Medical College & Hospital",
  chamber_bn: "খুলনা মেডিকেল কলেজ ও হাসপাতাল",
},

{
  name: "Associate Professor Lt. Col. Dr. Md. Mustafizul Islam",
  name_bn: "সহযোগী অধ্যাপক লে. কর্নেল ডা. মোঃ মোস্তাফিজুল ইসলাম",
  specialty: "surgery",
  specialty_bn: "সার্জারি বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Bangladesh Navy Hospital",
  hospital_bn: "বাংলাদেশ নৌবাহিনী হাসপাতাল",
  degree: "MBBS, MCPS, FCPS (Surgery)",
  degree_bn: "এমবিবিএস, এমসিপিএস, এফসিপিএস (সার্জারি)",
  phone: "01740-486127",
  schedule: "Sat - Thu (3:00 PM - 7:00 PM)",
  schedule_bn: "শনি - বৃহস্পতি (দুপুর ৩:০০ - সন্ধ্যা ৭:০০)",
  chamber: "Bangladesh Navy Hospital, Khulna",
  chamber_bn: "বাংলাদেশ নৌবাহিনী হাসপাতাল, খুলনা",
},

{
  name: "Dr. Lutes Surov Sarker",
  name_bn: "ডা. লুটেস সুরভ সরকার",
  specialty: "general",
  specialty_bn: "মেডিসিন বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Careta Khulna Region",
  hospital_bn: "কারেটা খুলনা অঞ্চল",
  degree: "MBBS, MCPS, Medicine",
  degree_bn: "এমবিবিএস, এমসিপিএস, মেডিসিন",
  phone: "01740-486128",
  schedule: "Sun - Thu (4:00 PM - 8:00 PM)",
  schedule_bn: "রবি - বৃহস্পতি (বিকাল ৪:০০ - রাত ৮:০০)",
  chamber: "Careta Khulna Region",
  chamber_bn: "কারেটা খুলনা অঞ্চল",
},

{
  name: "Dr. Abdul Basir Biswas",
  name_bn: "ডা. আব্দুল বাসির বিশ্বাস",
  specialty: "general",
  specialty_bn: "মেডিসিন বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "250 Bedded General Hospital",
  hospital_bn: "২৫০ শয্যা জেনারেল হাসপাতাল",
  degree: "MACP (USA)",
  degree_bn: "এমএসিপি (ইউএসএ)",
  phone: "01740-486129",
  schedule: "Sat - Wed (5:00 PM - 9:00 PM)",
  schedule_bn: "শনি - বুধ (বিকাল ৫:০০ - রাত ৯:০০)",
  chamber: "250 Bedded General Hospital, Khulna",
  chamber_bn: "২৫০ শয্যা জেনারেল হাসপাতাল, খুলনা",
},

{
  name: "Dr. Md. Al Aminul Islam",
  name_bn: "ডা. মোঃ আল আমিনুল ইসলাম",
  specialty: "cardiology",
  specialty_bn: "হৃদরোগ বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Khulna Medical College & Hospital",
  hospital_bn: "খুলনা মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS, BCS (Health), DLO (BSMMU)",
  degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), ডিএলও (বিএসএমএমইউ)",
  phone: "01740-486130",
  schedule: "Sun - Thu (5:00 PM - 8:00 PM)",
  schedule_bn: "রবি - বৃহস্পতি (বিকাল ৫:০০ - রাত ৮:০০)",
  chamber: "Khulna Medical College & Hospital",
  chamber_bn: "খুলনা মেডিকেল কলেজ ও হাসপাতাল",
},

{
  name: "Assistant Professor Dr. Tonmoy Reza Masum",
  name_bn: "সহকারী অধ্যাপক ডা. তন্ময় রেজা মাসুম",
  specialty: "general",
  specialty_bn: "মেডিসিন বিশেষজ্ঞ",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Institute of Nuclear Medicine & Allied Sciences",
  hospital_bn: "ইনস্টিটিউট অব নিউক্লিয়ার মেডিসিন অ্যান্ড অ্যালাইড সায়েন্সেস",
  degree: "MBBS, MD (Endocrinology)",
  degree_bn: "এমবিবিএস, এমডি (এন্ডোক্রিনোলজি)",
  phone: "01740-486131",
  schedule: "Sat - Thu (4:00 PM - 8:00 PM)",
  schedule_bn: "শনি - বৃহস্পতি (বিকাল ৪:০০ - রাত ৮:০০)",
  chamber: "Institute of Nuclear Medicine, Khulna",
  chamber_bn: "ইনস্টিটিউট অব নিউক্লিয়ার মেডিসিন, খুলনা",
},

{
  name: "Major Dr. Hossain Md. Erman",
  name_bn: "মেজর ডা. হোসাইন মোঃ এরমান",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Bangladesh Navy Hospital",
  hospital_bn: "বাংলাদেশ নৌবাহিনী হাসপাতাল",
  degree: "MBBS, DVD",
  degree_bn: "এমবিবিএস, ডিভিডি",
  phone: "01740-486132",
  schedule: "Sun - Thu (5:00 PM - 8:30 PM)",
  schedule_bn: "রবি - বৃহস্পতি (বিকাল ৫:০০ - রাত ৮:৩০)",
  chamber: "Bangladesh Navy Hospital, Khulna",
  chamber_bn: "বাংলাদেশ নৌবাহিনী হাসপাতাল, খুলনা",
},

{
  name: "Dr. Nargis Akter",
  name_bn: "ডা. নার্গিস আক্তার",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Khulna",
  division_bn: "খুলনা",
  hospital: "Sunrise Diagnostic & Consultation Center",
  hospital_bn: "সানরাইজ ডায়াগনস্টিক অ্যান্ড কনসালটেশন সেন্টার",
  degree: "MBBS, DDV",
  degree_bn: "এমবিবিএস, ডিডিভি",
  phone: "01740-486133",
  schedule: "Sat - Thu (4:00 PM - 7:30 PM)",
  schedule_bn: "শনি - বৃহস্পতি (বিকাল ৪:০০ - সন্ধ্যা ৭:৩০)",
  chamber: "Sunrise Diagnostic & Consultation Center, Khulna",
  chamber_bn: "সানরাইজ ডায়াগনস্টিক অ্যান্ড কনসালটেশন সেন্টার, খুলনা",
},
// ADD THESE INSIDE YOUR DOCTORS ARRAY

{
  name: "Dr. Md. Nazmus Saleheen (Pavel)",
  name_bn: "ডা. মোঃ নাজমুস সালেহীন (পাভেল)",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chattogram General Hospital",
  hospital_bn: "চট্টগ্রাম জেনারেল হাসপাতাল",
  degree: "MBBS, BCS (Health), DDV (Skin & Sex), CCD (BIRDEM), Fellowship in Dermatosurgery",
  degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), ডিডিভি, সিসিডি (বারডেম), ফেলোশিপ ইন ডার্মাটোসার্জারি",
  phone: " +8801777861289",
  schedule: "5 PM - 7 PM (Sat, Sun, Wed & Thu), 1:30 PM - 3 PM (Mon)",
  schedule_bn: "বিকাল ৫টা - ৭টা (শনি, রবি, বুধ ও বৃহস্পতি), দুপুর ১:৩০ - ৩টা (সোমবার)",
  chamber: "Epic Healthcare, Anderkilla, Chattogram",
  chamber_bn: "এপিক হেলথকেয়ার, আন্দরকিল্লা, চট্টগ্রাম",
},

{
  name: "Dr. Chowdhury Farhana Tinnee",
  name_bn: "ডা. চৌধুরী ফারহানা টিন্নী",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chittagong Medical College Hospital",
  hospital_bn: "চট্টগ্রাম মেডিকেল কলেজ হাসপাতাল",
  degree: "MBBS, MD (Dermatology & Venereology)",
  degree_bn: "এমবিবিএস, এমডি (ডার্মাটোলজি ও ভেনেরিওলজি)",
  phone: "+8801701297203",
  schedule: "2 PM - 4 PM (Everyday)",
  schedule_bn: "দুপুর ২টা - ৪টা (প্রতিদিন)",
  chamber: "Surecell Medical, Chattogram",
  chamber_bn: "শিওরসেল মেডিকেল, চট্টগ্রাম",
},

{
  name: "Dr. Md. Abul Hasem",
  name_bn: "ডা. মোঃ আবুল হাসেম",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Railway General Hospital",
  hospital_bn: "রেলওয়ে জেনারেল হাসপাতাল",
  degree: "MBBS, BCS (Health), DVD (BMU)",
  degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), ডিভিডি",
  phone: "01810-004550",
  schedule: "3 PM - 5 PM (Sat, Mon & Wed)",
  schedule_bn: "বিকাল ৩টা - ৫টা (শনি, সোম ও বুধ)",
  chamber: "Asperia Health Care Ltd, Chattogram",
  chamber_bn: "অ্যাসপেরিয়া হেলথ কেয়ার লিমিটেড, চট্টগ্রাম",
},

{
  name: "Dr. Tahmina Akhter Nishi",
  name_bn: "ডা. তাহমিনা আখতার নিশি",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chittagong Medical College & Hospital",
  hospital_bn: "চট্টগ্রাম মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS (CMC), BCS (Health), DDV (Skin & VD)",
  degree_bn: "এমবিবিএস (সিএমসি), বিসিএস (স্বাস্থ্য), ডিডিভি",
  phone: " +8801841962926",
  schedule: "3 PM - 6 PM (Closed: Thu & Fri)",
  schedule_bn: "বিকাল ৩টা - ৬টা (বন্ধ: বৃহস্পতি ও শুক্রবার)",
  chamber: "National Hospital, Chattogram",
  chamber_bn: "ন্যাশনাল হাসপাতাল, চট্টগ্রাম",
},

{
  name: "Dr. Sabina Yeasmin",
  name_bn: "ডা. সাবিনা ইয়াসমিন",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chittagong Medical College & Hospital",
  hospital_bn: "চট্টগ্রাম মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS, BCS (Health), MD (Dermatology & Venereology)",
  degree_bn: "এমবিবিএস, বিসিএস (স্বাস্থ্য), এমডি (ডার্মাটোলজি ও ভেনেরিওলজি)",
  phone: "01818-085865",
  schedule: "3:30 PM - 6:30 PM (Sun, Mon, Tue & Thu)",
  schedule_bn: "বিকাল ৩:৩০ - ৬:৩০ (রবি, সোম, মঙ্গল ও বৃহস্পতি)",
  chamber: "Epic Healthcare Ltd. (East Gate Branch), Chattogram",
  chamber_bn: "এপিক হেলথকেয়ার লিমিটেড (ইস্ট গেট শাখা), চট্টগ্রাম",
},

{
  name: "Dr. Shakti Chowdhury",
  name_bn: "ডা. শক্তি চৌধুরী",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chattogram Navy Hospital (Former)",
  hospital_bn: "চট্টগ্রাম নেভি হাসপাতাল (সাবেক)",
  degree: "MBBS (CMC), DDV (BSMMU)",
  degree_bn: "এমবিবিএস (সিএমসি), ডিডিভি (বিএসএমএমইউ)",
  phone: "+8801784330003",
  schedule: "3 PM - 5 PM (Closed: Friday)",
  schedule_bn: "বিকাল ৩টা - ৫টা (শুক্রবার বন্ধ)",
  chamber: "New Rabson Care, Chittagong",
  chamber_bn: "নিউ রবসন কেয়ার, চট্টগ্রাম",
},

{
  name: "Prof. Dr. Mansurul Alam",
  name_bn: "অধ্যাপক ডা. মনসুরুল আলম",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chittagong Medical College & Hospital",
  hospital_bn: "চট্টগ্রাম মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS, FCPS (Dermatology), MD (Skin & VD), PhD, FRCP (Glasgow)",
  degree_bn: "এমবিবিএস, এফসিপিএস (ডার্মাটোলজি), এমডি, পিএইচডি, এফআরসিপি",
  phone: "+8801984499600",
  schedule: "3:30 PM - 9 PM (Closed: Friday)",
  schedule_bn: "বিকাল ৩:৩০ - রাত ৯টা (শুক্রবার বন্ধ)",
  chamber: "Epic Healthcare, Chattogram",
  chamber_bn: "এপিক হেলথকেয়ার, চট্টগ্রাম",
},

{
  name: "Prof. Dr. Md. Shah Alam",
  name_bn: "অধ্যাপক ডা. মোঃ শাহ আলম",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chattogram Medical College & Hospital",
  hospital_bn: "চট্টগ্রাম মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS, DDV (DU), MD (Dermatology), Postdoctoral Fellow (USA)",
  degree_bn: "এমবিবিএস, ডিডিভি, এমডি (ডার্মাটোলজি), পোস্টডক্টরাল ফেলো",
  phone: "+8809666787810",
  schedule: "2:30 PM - 7 PM (Closed: Friday)",
  schedule_bn: "দুপুর ২:৩০ - সন্ধ্যা ৭টা (শুক্রবার বন্ধ)",
  chamber: "Popular Diagnostic Center, Chattogram",
  chamber_bn: "পপুলার ডায়াগনস্টিক সেন্টার, চট্টগ্রাম",
},

{
  name: "Prof. Dr. Md. Abul Kashem Chowdhury",
  name_bn: "অধ্যাপক ডা. মোঃ আবুল কাশেম চৌধুরী",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chittagong Medical College & Hospital",
  hospital_bn: "চট্টগ্রাম মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS, DDV, FCPS",
  degree_bn: "এমবিবিএস, ডিডিভি, এফসিপিএস",
  phone: "+8801766662828",
  schedule: "10 AM - 1 PM & 5 PM - 10 PM (Closed: Friday)",
  schedule_bn: "সকাল ১০টা - দুপুর ১টা এবং বিকাল ৫টা - রাত ১০টা (শুক্রবার বন্ধ)",
  chamber: "Labaid Specialized Hospital, Chattogram",
  chamber_bn: "ল্যাবএইড স্পেশালাইজড হাসপাতাল, চট্টগ্রাম",
},

{
  name: "Dr. Muhammad Manjurul Karim",
  name_bn: "ডা. মুহাম্মদ মনজুরুল করিম",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Apollo Imperial Hospital",
  hospital_bn: "অ্যাপোলো ইম্পেরিয়াল হাসপাতাল",
  degree: "MBBS, DD (Thailand), MSc (Dermatology)",
  degree_bn: "এমবিবিএস, ডিডি (থাইল্যান্ড), এমএসসি (ডার্মাটোলজি)",
  phone: "+8809612247247",
  schedule: "9 AM - 2 PM (Closed: Friday)",
  schedule_bn: "সকাল ৯টা - দুপুর ২টা (শুক্রবার বন্ধ)",
  chamber: "Apollo Imperial Hospital, Chattogram",
  chamber_bn: "অ্যাপোলো ইম্পেরিয়াল হাসপাতাল, চট্টগ্রাম",
},

{
  name: "Dr. Shamim Ara Sizu",
  name_bn: "ডা. শামীম আরা সিজু",
  specialty: "skin",
  specialty_bn: "ত্বক ক্যান্সার",
  division: "Chattogram",
  division_bn: "চট্টগ্রাম",
  hospital: "Chattagram International Medical College & Hospital",
  hospital_bn: "চট্টগ্রাম ইন্টারন্যাশনাল মেডিকেল কলেজ ও হাসপাতাল",
  degree: "MBBS, DDV, MD (Dermatology)",
  degree_bn: "এমবিবিএস, ডিডিভি, এমডি (ডার্মাটোলজি)",
  phone: "+8801976022333",
  schedule: "5 PM - 8 PM (Closed: Thu & Fri)",
  schedule_bn: "বিকাল ৫টা - রাত ৮টা (বৃহস্পতি ও শুক্রবার বন্ধ)",
  chamber: "Parkview Hospital, Chattogram",
  chamber_bn: "পার্কভিউ হাসপাতাল, চট্টগ্রাম",
},
];

export const SEED_DONORS: {
  name: string;
  group: BloodGroup;
  division: string;
  phone: string;
  source: string;
}[] = [
  {
    name: "Rakib Ahmed",
    group: "O+",
    division: "Dhaka",
    phone: "+8801711-000001",
    source: "Sandhani",
  },
  {
    name: "Nusrat Jahan",
    group: "A+",
    division: "Dhaka",
    phone: "+8801711-000002",
    source: "Quantum",
  },
  {
    name: "Tanvir Hasan",
    group: "B+",
    division: "Dhaka",
    phone: "+8801711-000003",
    source: "Badhan",
  },
  {
    name: "Mehnaz Karim",
    group: "AB+",
    division: "Dhaka",
    phone: "+8801711-000004",
    source: "Sandhani",
  },
  {
    name: "Sabbir Khan",
    group: "O-",
    division: "Chattogram",
    phone: "+8801812-000005",
    source: "Quantum",
  },
  {
    name: "Ishrat Binte",
    group: "A+",
    division: "Chattogram",
    phone: "+8801812-000006",
    source: "Badhan",
  },
  {
    name: "Rifat Chowdhury",
    group: "B+",
    division: "Sylhet",
    phone: "+8801913-000007",
    source: "Sandhani",
  },
  {
    name: "Anika Tabassum",
    group: "O+",
    division: "Khulna",
    phone: "+8801614-000008",
    source: "Quantum",
  },
  {
    name: "Hasibul Islam",
    group: "AB-",
    division: "Rajshahi",
    phone: "+8801515-000009",
    source: "Sandhani",
  },
  {
    name: "Mim Akter",
    group: "A-",
    division: "Barishal",
    phone: "+8801416-000010",
    source: "Badhan",
  },
  {
    name: "Sajid Rahman",
    group: "O+",
    division: "Rangpur",
    phone: "+8801317-000011",
    source: "Sandhani",
  },
  {
    name: "Farzana Yeasmin",
    group: "B-",
    division: "Mymensingh",
    phone: "+8801218-000012",
    source: "Quantum",
  },
];