/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as MentalRouteImport } from './routes/mental'
import { Route as MedicineRouteImport } from './routes/medicine'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as CancerRouteImport } from './routes/cancer'
import { Route as BloodRouteImport } from './routes/blood'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const MentalRoute = MentalRouteImport.update({
  id: '/mental',
  path: '/mental',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicineRoute = MedicineRouteImport.update({
  id: '/medicine',
  path: '/medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const CancerRoute = CancerRouteImport.update({
  id: '/cancer',
  path: '/cancer',
  getParentRoute: () => rootRouteImport,
} as any)
const BloodRoute = BloodRouteImport.update({
  id: '/blood',
  path: '/blood',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blood': typeof BloodRoute
  '/cancer': typeof CancerRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/medicine': typeof MedicineRoute
  '/mental': typeof MentalRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blood': typeof BloodRoute
  '/cancer': typeof CancerRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/medicine': typeof MedicineRoute
  '/mental': typeof MentalRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blood': typeof BloodRoute
  '/cancer': typeof CancerRoute
  '/doctors': typeof DoctorsRoute
  '/login': typeof LoginRoute
  '/medicine': typeof MedicineRoute
  '/mental': typeof MentalRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blood'
    | '/cancer'
    | '/doctors'
    | '/login'
    | '/medicine'
    | '/mental'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blood'
    | '/cancer'
    | '/doctors'
    | '/login'
    | '/medicine'
    | '/mental'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/blood'
    | '/cancer'
    | '/doctors'
    | '/login'
    | '/medicine'
    | '/mental'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BloodRoute: typeof BloodRoute
  CancerRoute: typeof CancerRoute
  DoctorsRoute: typeof DoctorsRoute
  LoginRoute: typeof LoginRoute
  MedicineRoute: typeof MedicineRoute
  MentalRoute: typeof MentalRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mental': {
      id: '/mental'
      path: '/mental'
      fullPath: '/mental'
      preLoaderRoute: typeof MentalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medicine': {
      id: '/medicine'
      path: '/medicine'
      fullPath: '/medicine'
      preLoaderRoute: typeof MedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cancer': {
      id: '/cancer'
      path: '/cancer'
      fullPath: '/cancer'
      preLoaderRoute: typeof CancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blood': {
      id: '/blood'
      path: '/blood'
      fullPath: '/blood'
      preLoaderRoute: typeof BloodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BloodRoute: BloodRoute,
  CancerRoute: CancerRoute,
  DoctorsRoute: DoctorsRoute,
  LoginRoute: LoginRoute,
  MedicineRoute: MedicineRoute,
  MentalRoute: MentalRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
